[project]
name = "drssionpagemcp"
version = "0.1.0"
description = "A Python package for the Drissionpage MCP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "drissionpage>=4.1.0.18",
    "fastmcp>=2.4.0",
]


[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"